image: gitpod/workspace-full

ports:
- port: 3000
  onOpen: open-preview

tasks:
  - before: >
      npm install -g pnpm
  - init: |
      pnpm install
    command: |
      pnpm dev
  - command: gp await-port 3000 && gp preview "$(gp url 3000)/"
